<a href="https://colab.research.google.com/github/priyaking3803-tech/Business-Reputation-Insights-Analyzer-using-Google-Maps-Reviews-/blob/main/Copy_of_businesspynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# @title
import requests
import pandas as pd


place_ids = {
    "Eiffel Tower — Paris, France": "ChIJLU7jZClu5kcR4PcOOO6p3I0",
    "Statue of Liberty National Monument — New York, USA": "ChIJPTacEpBQwokRKwIlDXelxkA",
    "Sydney Opera House — Sydney, Australia": "ChIJ3S-JXmauEmsRUcIaWtf4MzE",
    "Colosseum — Rome, Italy": "ChIJxQKkFeRbzEcRaPJT8-hbZL4",
    "Christ the Redeemer — Rio de Janeiro, Brazil": "ChIJpQdQg8S5EwcR9n7TSaue1i4",
    "Louvre Museum in Paris": "ChIJLU7jZClu5kcR4PcOOO6p3I0",
    "Great Wall of China — Huairou, China": "ChIJVXealY3t8TQRs9r7z2w5v0g",
    "Taj Mahal — Agra, India": "ChIJ2eUgeAK6j4ARbn5u_wAGqWA",
    "Machu Picchu — Cusco Region, Peru": "ChIJGzE9DS1YzTERK2p8b7J4U8Q",
    "Pyramids of Giza — Giza, Egypt": "ChIJ3cX1pQ1vWBQRi5w4Y0b6X0E"
}

# Step 1: API parameters
params = {
    "engine": "google_maps_reviews",
    "place_id": "ChIJLU7jZClu5kcR4PcOOO6p3I0",  # Example: Louvre Museum in Paris
    "hl": "en",
    "api_key": "e98121f8055751ee6ff3eaafd8f4159bdee39e53546a909e9cc4de080bf80a79"
}

# Step 2: API request
url = "https://serpapi.com/search.json"
response = requests.get(url, params=params)

# Step 3: Parse reviews
reviews = response.json().get("reviews", [])

# Step 4: Save to DataFrame
df = pd.DataFrame(reviews)
df.to_csv("google_reviews.csv", index=False)

print("✅ Collected", len(df), "reviews")
df.head()

✅ Collected 8 reviews

,link,rating,date,iso_date,iso_date_of_last_edit,images,source,review_id,user,snippet,extracted_snippet,details
0,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a week ago,2025-12-18T11:25:52Z,2025-12-18T11:25:52Z,[https://lh3.googleusercontent.com/geougc-cs/A...,Google,Ci9DQUlRQUNvZENodHljRjlvT2tOb1FsQTNRVmRZTVZsaV...,"{'name': 'L A K', 'link': 'https://www.google....",The Eiffel Tower is honestly better in real li...,{'original': 'The Eiffel Tower is honestly bet...,"{'visited_on': 'Public holiday', 'wait_time': ..."
1,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a week ago,2025-12-13T18:29:44Z,2025-12-13T18:29:44Z,[https://lh3.googleusercontent.com/geougc-cs/A...,Google,Ci9DQUlRQUNvZENodHljRjlvT25aZldtdGlabFp5VVdjeG...,"{'name': 'Muhammad Abubakar', 'link': 'https:/...",The place does have its own charm. Expect it t...,{'original': 'The place does have its own char...,"{'visited_on': 'Weekday', 'wait_time': 'No wai..."
2,https://www.google.com/maps/reviews/data=!4m8!...,5.0,Edited 2 weeks ago,2025-12-08T00:15:14Z,2025-12-10T17:56:54Z,[https://lh3.googleusercontent.com/geougc-cs/A...,Google,Ci9DQUlRQUNvZENodHljRjlvT2poZlIzUktjbkJPZDE5M2...,"{'name': 'steve D', 'link': 'https://www.googl...",I could only buy a lift access ticket online a...,{'original': 'I could only buy a lift access t...,"{'visited_on': 'Weekend', 'wait_time': 'Up to ..."
3,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a week ago,2025-12-11T13:13:41Z,2025-12-11T13:13:41Z,[https://lh3.googleusercontent.com/geougc-cs/A...,Google,Ci9DQUlRQUNvZENodHljRjlvT2pSRmQwNXhWV3Q1ZEUxR1...,"{'name': 'Andrew Cranwell', 'link': 'https://w...",It's the place to visit when you come to Paris...,{'original': 'It's the place to visit when you...,"{'visited_on': 'Weekday', 'wait_time': 'No wai..."
4,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a week ago,2025-12-16T23:37:56Z,2025-12-16T23:37:56Z,[https://lh3.googleusercontent.com/geougc-cs/A...,Google,Ci9DQUlRQUNvZENodHljRjlvT2xGdGJrZHRUWFF4VkVRdG...,"{'name': 'Mariia Udymovych', 'link': 'https://...",One of the most beautiful places where I have ...,{'original': 'One of the most beautiful places...,"{'visited_on': 'Weekday', 'wait_time': 'Up to ..."

In [ ]:
import pandas as pd
df = pd.read_csv("google_reviews.csv")
df

,link,rating,date,iso_date,iso_date_of_last_edit,images,source,review_id,user,snippet,extracted_snippet,details
0,https://www.google.com/maps/reviews/data=!4m8!...,4.0,6 days ago,2025-11-19T09:43:40Z,2025-11-19T09:43:40Z,['https://lh3.googleusercontent.com/geougc-cs/...,Google,Ci9DQUlRQUNvZENodHljRjlvT2psaE1GTkhhMGgwYWpJM1...,"{'name': 'Timothy Pang', 'link': 'https://www....","Well, if one is in Paris it’s hard not to visi...","{'original': 'Well, if one is in Paris it’s ha...","{'visited_on': 'Weekday', 'wait_time': '10–30 ..."
1,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a month ago,2025-10-22T08:11:40Z,2025-10-22T08:11:40Z,['https://lh3.googleusercontent.com/geougc-cs/...,Google,Ci9DQUlRQUNvZENodHljRjlvT25wMU0zQmhMVmgzZURCc2...,"{'name': 'Amrit Das', 'link': 'https://www.goo...",•\tNo ticket needed: You don’t have to buy a t...,{'original': '•\tNo ticket needed: You don’t h...,"{'visited_on': 'Weekday', 'wait_time': 'No wai..."
2,https://www.google.com/maps/reviews/data=!4m8!...,4.0,6 days ago,2025-11-19T11:26:16Z,2025-11-19T11:26:16Z,['https://lh3.googleusercontent.com/geougc-cs/...,Google,Ci9DQUlRQUNvZENodHljRjlvT21VellrTjVkRGh2VmxZME...,"{'name': 'Ezeobiakor Izuchukwu', 'link': 'http...",🇫🇷 An Essential Paris Experience: Unforgettabl...,"{'original': ""🇫🇷 An Essential Paris Experience...",NaN
3,https://www.google.com/maps/reviews/data=!4m8!...,5.0,Edited 2 weeks ago,2025-10-26T23:38:48Z,2025-11-08T13:04:20Z,['https://lh3.googleusercontent.com/geougc-cs/...,Google,Ci9DQUlRQUNvZENodHljRjlvT2pkelpHSjJjV3BxYkZaU1...,"{'name': 'Jay Kothari', 'link': 'https://www.g...",Great view from the top (actually 2nd floor is...,"{'original': ""Great view from the top (actuall...","{'visited_on': 'Weekday', 'wait_time': 'Up to ..."
4,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a month ago,2025-10-02T20:41:44Z,2025-10-03T12:48:26Z,['https://lh3.googleusercontent.com/geougc-cs/...,Google,Ci9DQUlRQUNvZENodHljRjlvT2pWcFNYVldZMFJ3YTNkVV...,"{'name': 'Aryan Patel', 'link': 'https://www.g...",A Magical Day at the Eiffel Tower\n\nI visited...,{'original': 'A Magical Day at the Eiffel Towe...,"{'visited_on': 'Weekday', 'wait_time': '30–60 ..."
5,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a week ago,2025-11-18T16:22:09Z,2025-11-18T16:22:09Z,['https://lh3.googleusercontent.com/geougc-cs/...,Google,Ci9DQUlRQUNvZENodHljRjlvT2xsdFFXRnVXVUpLUVdaU1...,"{'name': 'Chloe Brentnall', 'link': 'https://w...",A beautiful day at the Eiffel Tower\n\nI didn’...,{'original': 'A beautiful day at the Eiffel To...,"{'visited_on': 'Weekday', 'wait_time': 'No wai..."
6,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a week ago,2025-11-18T16:25:53Z,2025-11-18T16:25:53Z,['https://lh3.googleusercontent.com/geougc-cs/...,Google,Ci9DQUlRQUNvZENodHljRjlvT2pGSmJGaElSQzFEU0Rkdl...,"{'name': 'Carl Frost', 'link': 'https://www.go...",We walked up the stairs to the second floor wh...,{'original': 'We walked up the stairs to the s...,"{'visited_on': 'Weekday', 'wait_time': 'No wai..."
7,https://www.google.com/maps/reviews/data=!4m8!...,5.0,a week ago,2025-11-18T07:27:58Z,2025-11-18T07:27:58Z,['https://lh3.googleusercontent.com/geougc-cs/...,Google,Ci9DQUlRQUNvZENodHljRjlvT25KUFoyVXhZbkZ4VUZaeG...,"{'name': 'Giorgi Mikeladze', 'link': 'https://...",The Most Iconic Photo Backdrop in the World!\n...,"{'original': ""The Most Iconic Photo Backdrop i...","{'visited_on': 'Weekend', 'wait_time': 'No wai..."

In [ ]:
df.columns

Index(['link', 'rating', 'date', 'iso_date', 'iso_date_of_last_edit', 'images',
       'source', 'review_id', 'user', 'snippet', 'extracted_snippet',
       'details'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   link                   8 non-null      object
 1   rating                 8 non-null      float64
 2   date                   8 non-null      object
 3   iso_date               8 non-null      object
 4   iso_date_of_last_edit  8 non-null      object
 5   images                 8 non-null      object
 6   source                 8 non-null      object
 7   review_id              8 non-null      object
 8   user                   8 non-null      object
 9   snippet                8 non-null      object
 10  extracted_snippet      8 non-null      object
 11  details                7 non-null      object
dtypes: float64(1), object(11)
memory usage: 900.0+ bytes

In [ ]:
import ast

df['user'] = df['user'].apply(ast.literal_eval)

In [ ]:
df['user'] = df['user'].apply(lambda x: x['name'] if isinstance(x, dict) and 'name' in x else None)

In [ ]:
df = df[['user','rating','iso_date','snippet']]

In [ ]:
df.head()

,user,rating,iso_date,snippet
0,Timothy Pang,4.0,2025-11-19T09:43:40Z,"Well, if one is in Paris it’s hard not to visi..."
1,Amrit Das,5.0,2025-10-22T08:11:40Z,•\tNo ticket needed: You don’t have to buy a t...
2,Ezeobiakor Izuchukwu,4.0,2025-11-19T11:26:16Z,🇫🇷 An Essential Paris Experience: Unforgettabl...
3,Jay Kothari,5.0,2025-10-26T23:38:48Z,Great view from the top (actually 2nd floor is...
4,Aryan Patel,5.0,2025-10-02T20:41:44Z,A Magical Day at the Eiffel Tower\n\nI visited...

In [ ]:
!pip install emoji
import emoji

def remove_emojis_lib(text):
    return emoji.replace_emoji(text, replace="")
df['cleaned_snippet'] = df['snippet'].apply(remove_emojis_lib)

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 10.9 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

/tmp/ipython-input-289041663.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_snippet'] = df['snippet'].apply(remove_emojis_lib)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = re.sub(r"http\S+", "", text)  # Remove URLs
    text = re.sub(r"[^a-zA-Z\s]", "", text)  # Remove numbers/special chars
    text = text.lower()  # Lowercase
    tokens = nltk.word_tokenize(text)
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return " ".join(tokens)
df['cleaned_snippet'] = df['cleaned_snippet'].apply(clean_text)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
/tmp/ipython-input-2144382168.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_snippet'] = df['cleaned_snippet'].apply(clean_text)

In [ ]:
df

,user,rating,iso_date,snippet,cleaned_snippet
0,Timothy Pang,4.0,2025-11-19T09:43:40Z,"Well, if one is in Paris it’s hard not to visi...",well one paris hard visit queue long best get ...
1,Amrit Das,5.0,2025-10-22T08:11:40Z,•\tNo ticket needed: You don’t have to buy a t...,ticket needed dont buy ticket enter tower queu...
2,Ezeobiakor Izuchukwu,4.0,2025-11-19T11:26:16Z,🇫🇷 An Essential Paris Experience: Unforgettabl...,essential paris experience unforgettable view ...
3,Jay Kothari,5.0,2025-10-26T23:38:48Z,Great view from the top (actually 2nd floor is...,great view top actually nd floor enough dont g...
4,Aryan Patel,5.0,2025-10-02T20:41:44Z,A Magical Day at the Eiffel Tower\n\nI visited...,magical day eiffel tower visited eiffel tower ...
5,Chloe Brentnall,5.0,2025-11-18T16:22:09Z,A beautiful day at the Eiffel Tower\n\nI didn’...,beautiful day eiffel tower didnt go top time e...
6,Carl Frost,5.0,2025-11-18T16:25:53Z,We walked up the stairs to the second floor wh...,walked stair second floor right mission worth ...
7,Giorgi Mikeladze,5.0,2025-11-18T07:27:58Z,The Most Iconic Photo Backdrop in the World!\n...,iconic photo backdrop world photographer ive s...

In [ ]:
df.drop(columns=['snippet'], inplace=True)

/tmp/ipython-input-3508380770.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['snippet'], inplace=True)

In [ ]:
df.to_csv("cleaned_google_reviews.csv", index=False)

In [ ]:
import pandas as pd
df = pd.read_csv("cleaned_google_reviews.csv")
df.head()

,user,rating,iso_date,cleaned_snippet
0,Timothy Pang,4.0,2025-11-19T09:43:40Z,well one paris hard visit queue long best get ...
1,Amrit Das,5.0,2025-10-22T08:11:40Z,ticket needed dont buy ticket enter tower queu...
2,Ezeobiakor Izuchukwu,4.0,2025-11-19T11:26:16Z,essential paris experience unforgettable view ...
3,Jay Kothari,5.0,2025-10-26T23:38:48Z,great view top actually nd floor enough dont g...
4,Aryan Patel,5.0,2025-10-02T20:41:44Z,magical day eiffel tower visited eiffel tower ...

In [ ]:
print(df['cleaned_snippet'].iloc[1])

ticket needed dont buy ticket enter tower queue elevatorsjust pick great external vantage youre free shoot pace excellent photo spot nearby many welldocumented location give iconic tower view outsideeg rue de luniversit rue de buenosaires avenue de camons spot highlighted photographer guide hidden lesscrowded alternative flexible timing youre tied ticket time go early morning late evening twilight capture different lighting mood lower cost skipping entrance mean saving time money focusing instead view atmosphere great casual photographic visit priority tower photo rather ascending approach work perfectly keep mind miss inside experience wont go tower see internal architecture get panoramic view heightsits purely outside vantage experience crowdslines possible popular spot even external photo spot crowded especially popular one like trocadro rue de luniversit guide warn many people even street viewpoint lighting viewpoint selection matter good photo depend heavily time day weather background composition street river building go wrong time may get harsh light less dramatic angle expect standard viewpoint secret many external spot appear photospot guide social medium youre entering tower might share view others still costtime go trip youll still invest time walking transport reach good baseline vantage

In [ ]:
all_reviews = " ".join(df['cleaned_snippet'].tolist())

In [ ]:
all_reviews

'well one paris hard visit queue long best get early prepared wait ticket expensive splendid view top course particularly clear day overall well worth visit one fun family although small child may get bored wait less impressed ticket needed dont buy ticket enter tower queue elevatorsjust pick great external vantage youre free shoot pace excellent photo spot nearby many welldocumented location give iconic tower view outsideeg rue de luniversit rue de buenosaires avenue de camons spot highlighted photographer guide hidden lesscrowded alternative flexible timing youre tied ticket time go early morning late evening twilight capture different lighting mood lower cost skipping entrance mean saving time money focusing instead view atmosphere great casual photographic visit priority tower photo rather ascending approach work perfectly keep mind miss inside experience wont go tower see internal architecture get panoramic view heightsits purely outside vantage experience crowdslines possible popular spot even external photo spot crowded especially popular one like trocadro rue de luniversit guide warn many people even street viewpoint lighting viewpoint selection matter good photo depend heavily time day weather background composition street river building go wrong time may get harsh light less dramatic angle expect standard viewpoint secret many external spot appear photospot guide social medium youre entering tower might share view others still costtime go trip youll still invest time walking transport reach good baseline vantage essential paris experience unforgettable view history visiting eiffel tower highlight trip paris even cloudy day structure breathtaking base sheer scale engineering incredible making truly iconic landmark experience took time go one platform highly recommend view paris spectacular giving completely different perspective city inside lattice work tower experience especially appreciated historical information available different level detailing construction use early radio transmission add much context magnificent monument tip visitor book ticket advance line long prebooking essential save time allow plenty time security check queue lift plenty thing see youre dont rush experience photo ops viewing platform offer incredible spot family photo framed beautiful ironwork city overall eiffel tower mustsee landmark life reputation highly recommended visitor paris great view top actually nd floor enough dont go way top unless want pay extra imho metal took year month amd day put together step st floor probably similar nd floor bathroom floor thankfully feel earned right take elevator back make sure buy online ticket advance get booked fast also eticket get fast line magical day eiffel tower visited eiffel tower today absolutely lived hype moment stepped onto champ de mar iron lady latticework felt grand surprisingly graceful view top breathtakingparis stretch every direction like living postcard seine curving city landmark popping everywhere look experience felt smooth wellorganized staff friendly even crowd line moved faster expected loved taking time leveltheres something special pausing coffee soaking panorama evening fell tower sparkle made whole scene feel downright romantic cinematic youre planning visit id recommend booking ticket ahead time going bit sunset catch daylight golden hour first twinkle dark whether take elevator brave stair journey part fun today visit unforgettable eiffel tower isnt mustseeits mustfeel five star beautiful day eiffel tower didnt go top time even ground eiffel tower incredible atmosphere around something special walked back along seine afterwards beautifully crisp day calm bright perfect taking everything sometimes simple moment best one highly recommend visit even youre wandering around area walked stair second floor right mission worth view walk brilliant refreshment stop heading top via elevator stunning view city clear fine day iconic photo backdrop world photographer ive shot many beautiful place nothing compare magic eiffel tower recently photoshoot location simply breathtaking landmark heart paris architecture stunning every angle whether shooting trocadro classic view bank seine even charming side street yes crowded part vibrant atmosphere result always worth photo arent picture timeless memory filled romance parisian charm couple individual wanting capture spirit paris location im attaching photo session show beauty'